# Generated by Django 3.1.2 on 2023-07-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0006_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='Valor padrão', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(default='Valor padrão', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default='Valor padrão', max_length=10),
        ),
    ]
