# Generated by Django 4.2.3 on 2023-07-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0007_auto_20230703_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='000000000000000', max_length=11),
        ),
    ]
